language: objective-c
before_install: 
    - export LANG=en_US.UTF-8
    - rake install
script: 
    - rake clean:example
    - rake test
    - rake analyze
notifications:
    email:
        recipients:
         - michael.gorbach@raizlabs.com
         - matt.buckley@raizlabs.com
        on_success: change
        on_failure: always